#!/usr/bin/env python3
"""
Fetch mean number of authors per paper from OpenAlex.

Queries the OpenAlex API for biomedical journal articles by year,
samples works, and computes the mean author count.

Output: ../public/figures/author-count-growth.yaml

OpenAlex API docs: https://docs.openalex.org/
No API key required (polite pool with mailto).
"""

import json
import os
import statistics
import sys
import time

import requests
import yaml

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

YEARS = list(range(2003, 2026, 2))          # every 2 years
SAMPLE_SIZE = 200                            # works to sample per year
MAILTO = "jeromel@alleninstitute.org"        # for OpenAlex polite pool
OUTPUT = os.path.join(
    os.path.dirname(__file__), "..", "public", "figures", "author-count-growth.yaml"
)

# OpenAlex concept IDs for biomedical / life sciences
# "Medicine" (C71924100) and "Biology" (C86803240)
CONCEPT_FILTER = "concepts.id:C71924100|C86803240"

API_BASE = "https://api.openalex.org/works"

# ---------------------------------------------------------------------------
# Fetch
# ---------------------------------------------------------------------------


def fetch_mean_authors(year: int) -> dict:
    """Return {year, mean, median, sample_size} for a given publication year."""
    params = {
        "filter": f"publication_year:{year},type:article,{CONCEPT_FILTER}",
        "per_page": SAMPLE_SIZE,
        "select": "id,authorships",
        "mailto": MAILTO,
        # Use a cursor-based sample — first page is effectively random-ish
        "sort": "cited_by_count:desc",
    }

    resp = requests.get(API_BASE, params=params, timeout=30)
    resp.raise_for_status()
    data = resp.json()

    results = data.get("results", [])
    if not results:
        print(f"  WARNING: no results for {year}", file=sys.stderr)
        return {"year": year, "mean": 0, "median": 0, "sample_size": 0}

    author_counts = [len(w.get("authorships", [])) for w in results]

    mean_val = round(statistics.mean(author_counts), 2)
    median_val = round(statistics.median(author_counts), 1)

    return {
        "year": year,
        "mean": mean_val,
        "median": median_val,
        "sample_size": len(author_counts),
    }


def main():
    print(f"Fetching author counts from OpenAlex ({len(YEARS)} years)...")
    data_points = []

    for year in YEARS:
        print(f"  {year}...", end=" ", flush=True)
        result = fetch_mean_authors(year)
        print(f"mean={result['mean']}, median={result['median']}, n={result['sample_size']}")
        data_points.append(result)
        time.sleep(0.2)  # be polite

    # Build output YAML
    output = {
        "title": "Mean authors per paper in biomedical sciences",
        "xLabel": "Year",
        "yLabel": "Mean authors per paper",
        "source": "OpenAlex API (https://openalex.org). "
                  "Filtered to journal articles in Medicine and Biology concepts. "
                  f"Sample of {SAMPLE_SIZE} highly-cited articles per year.",
        "generated": time.strftime("%Y-%m-%d"),
        "data": [{"year": d["year"], "mean": d["mean"], "median": d["median"]} for d in data_points],
    }

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write("# ============================================================\n")
        f.write("# Mean number of authors per paper over time\n")
        f.write("# ============================================================\n")
        f.write("# AUTO-GENERATED by figures/fetch_author_count_growth.py\n")
        f.write(f"# Generated: {output['generated']}\n")
        f.write(f"# Source: {output['source']}\n")
        f.write("# ============================================================\n\n")
        yaml.dump(output, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    print(f"\nWritten to {os.path.abspath(OUTPUT)}")

    # Also print a summary table
    print("\nYear  Mean  Median  N")
    print("-" * 30)
    for d in data_points:
        print(f"{d['year']}  {d['mean']:5.2f}  {d['median']:5.1f}  {d['sample_size']:4d}")


if __name__ == "__main__":
    main()
